version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foodclassifierapp-app-1
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "app.py"]
